[tools]
lute = { source = "luau-lang/lute", version = "=0.1.0-nightly.20260113" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "2.0.1" }
rojo = { source = "Roblox/rojo-rbx-rojo", version = "7.3.0" }
